2021-09-20 18:42:19,429 INFO    MainThread:61766 [wandb_setup.py:_flush():69] setting env: {}
2021-09-20 18:42:19,429 INFO    MainThread:61766 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-20 18:42:19,429 INFO    MainThread:61766 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '0bc47cb35cb42f3f15ce4f1252a2484b84c0bf59'}
2021-09-20 18:42:19,429 INFO    MainThread:61766 [wandb_init.py:_log_setup():348] Logging user logs to /Users/robertreynoso/Desktop/phase_03_project/notebooks/wandb/run-20210920_184219-1npizsje/logs/debug.log
2021-09-20 18:42:19,429 INFO    MainThread:61766 [wandb_init.py:_log_setup():349] Logging internal logs to /Users/robertreynoso/Desktop/phase_03_project/notebooks/wandb/run-20210920_184219-1npizsje/logs/debug-internal.log
2021-09-20 18:42:19,430 INFO    MainThread:61766 [wandb_init.py:init():381] calling init triggers
2021-09-20 18:42:19,430 INFO    MainThread:61766 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-20 18:42:19,430 INFO    MainThread:61766 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 1wxfldbk
2021-09-20 18:42:19,432 INFO    MainThread:61766 [wandb_run.py:finish():1275] finishing run reynoso811/sklearn/1wxfldbk
2021-09-20 18:42:19,439 INFO    MainThread:61766 [jupyter.py:save_history():353] not saving jupyter history
2021-09-20 18:42:19,440 INFO    MainThread:61766 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-20 18:42:19,440 INFO    MainThread:61766 [wandb_init.py:_jupyter_teardown():281] cleaning up jupyter logic
2021-09-20 18:42:19,440 INFO    MainThread:61766 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-20 18:42:19,440 INFO    MainThread:61766 [wandb_run.py:_restore():1547] restore
2021-09-20 18:42:19,534 INFO    MainThread:61766 [wandb_run.py:_restore():1547] restore
2021-09-20 18:42:19,557 ERROR   MainThread:61766 [wandb_init.py:init():830] error
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1583, in _atexit_cleanup
    self._on_finish()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1740, in _on_finish
    self._backend.interface.publish_telemetry(self._telemetry_obj)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 228, in publish_telemetry
    self._publish(rec)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 530, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 803, in init
    run = wi.init()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 418, in init
    self._wl._global_run_stack[-1].finish()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1279, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1592, in _atexit_cleanup
    self._backend.cleanup()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
    self.interface.join()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 830, in join
    _ = self._communicate(record)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2021-09-20 18:44:11,877 INFO    MainThread:61766 [wandb_run.py:_config_callback():847] config_cb ('_wandb', 'viz', 'learning_curve') {'id': 'wandb/learning_curve/v1', 'historyFieldSettings': {'key': 'learning_curve', 'x-axis': '_step'}} None
2021-09-20 18:44:31,050 INFO    MainThread:61766 [wandb_setup.py:_flush():69] setting env: {}
2021-09-20 18:44:31,051 INFO    MainThread:61766 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-20 18:44:31,051 INFO    MainThread:61766 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '0bc47cb35cb42f3f15ce4f1252a2484b84c0bf59'}
2021-09-20 18:44:31,051 INFO    MainThread:61766 [wandb_init.py:_log_setup():348] Logging user logs to /Users/robertreynoso/Desktop/phase_03_project/notebooks/wandb/run-20210920_184431-3j2ggua8/logs/debug.log
2021-09-20 18:44:31,051 INFO    MainThread:61766 [wandb_init.py:_log_setup():349] Logging internal logs to /Users/robertreynoso/Desktop/phase_03_project/notebooks/wandb/run-20210920_184431-3j2ggua8/logs/debug-internal.log
2021-09-20 18:44:31,052 INFO    MainThread:61766 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9cd1c613d0>
2021-09-20 18:44:31,053 INFO    MainThread:61766 [wandb_init.py:init():381] calling init triggers
2021-09-20 18:44:31,053 INFO    MainThread:61766 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-20 18:44:31,053 INFO    MainThread:61766 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 1wxfldbk
2021-09-20 18:44:31,055 INFO    MainThread:61766 [wandb_run.py:finish():1275] finishing run reynoso811/sklearn/1wxfldbk
2021-09-20 18:44:31,056 INFO    MainThread:61766 [wandb_init.py:init():430] starting backend
2021-09-20 18:44:31,057 INFO    MainThread:61766 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-09-20 18:44:31,060 INFO    MainThread:61766 [backend.py:ensure_launched():135] starting backend process...
2021-09-20 18:44:31,077 INFO    MainThread:61766 [backend.py:ensure_launched():139] started backend process with pid: 62368
2021-09-20 18:44:31,080 INFO    MainThread:61766 [wandb_init.py:init():435] backend started and connected
2021-09-20 18:44:31,101 INFO    MainThread:61766 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-20 18:44:31,102 INFO    MainThread:61766 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-20 18:44:31,102 INFO    MainThread:61766 [wandb_init.py:init():494] updated telemetry
2021-09-20 18:44:31,103 INFO    MainThread:61766 [wandb_init.py:init():517] communicating current version
2021-09-20 18:44:32,063 INFO    MainThread:61766 [wandb_init.py:init():522] got version response 
2021-09-20 18:44:32,063 INFO    MainThread:61766 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-20 18:44:32,207 INFO    MainThread:61766 [wandb_init.py:init():557] starting run threads in backend
2021-09-20 18:44:37,230 INFO    MainThread:61766 [wandb_run.py:_console_start():1605] atexit reg
2021-09-20 18:44:37,233 INFO    MainThread:61766 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-20 18:44:37,234 INFO    MainThread:61766 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-20 18:44:37,238 INFO    MainThread:61766 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-20 18:44:37,240 INFO    MainThread:61766 [wandb_init.py:init():582] run started, returning control to user process
2021-09-20 18:44:37,250 INFO    MainThread:61766 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-20 18:44:37,251 INFO    MainThread:61766 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-20 18:47:34,963 INFO    MainThread:61766 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-20 18:47:34,981 INFO    MainThread:61766 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-20 18:47:34,981 INFO    MainThread:61766 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-20 18:51:52,987 INFO    MainThread:61766 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-20 18:51:52,993 INFO    MainThread:61766 [wandb_run.py:_restore():1547] restore
2021-09-20 18:51:53,181 INFO    MainThread:61766 [wandb_run.py:_restore():1547] restore
